name: CI

on: [ push, pull_request ]

jobs:
  create-virtualenv:
    environment: Test Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - run: pip install -r requirements-test.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - run: pip install flake8 black
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

  linter:
    environment: Test Run
    needs: create-virtualenv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - run: flake8 --max-line-length=127 --ignore=E203,W503 --exclude=venv
      - run: black --check --diff .

  tests:
    environment: Test Run
    needs: create-virtualenv
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - run: py.test
